import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastProvider } from "../../providers/toast_provider";

const poppins = Poppins({
  subsets: ["latin"],weight:["100",'200','300','400'],
});


export const metadata: Metadata = {
  title: "Online JOb Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
     className={poppins.className}
      >
        {children}
<ToastProvider />
      </body>
    </html>
    </ClerkProvider>
  );
}
